Added map web component shadow paths styling example
datacommonsorg/website pull request #2907
Opened 2023-07-07 23:03 UTC by dwnoble

Example of web component styling using shadow paths

Screenshot: Styled (top), unstyled (bottom)

![styled-map](https://github.com/datacommonsorg/website/assets/13766/83da627f-6917-4b20-9682-2411665e227b)

2023-07-10 22:34 UTC, juliawu approved these changes
This is super cool!

2023-07-10 22:34 UTC, juliawu commented on web-components/examples/example.html
> +    <style>
Let's add a comment that this is some example CSS you can add to do custom styling of the components.

2023-07-11 22:06 UTC, juliawu commented on web-components/examples/example.html
> +      comparisonPlaces='["geoId/01", "geoId/02", "geoId/04", "geoId/05"]'
Let's stick with space separated lists in the examples.

2023-07-11 22:07 UTC, juliawu commented on web-components/examples/example.html
> +      variables='["Mean_PalmerDroughtSeverityIndex"]'
Let's also go with space separated lists for `variables` in these examples.

2023-07-11 22:07 UTC, juliawu requested changes
Looks good! Let's just standardize space separated lists now that that change is in.

2023-07-11 23:11 UTC, dwnoble commented
Thanks Julia- made those changes.

2023-07-11 23:13 UTC, juliawu approved these changes
Awesome! Thanks for all the changes!

2023-07-12 05:53 UTC, merged