Tile Icons Part 1: Add download and explore link icons
datacommonsorg/website pull request #4224
Opened 2024-05-13 17:58 UTC by juliawu

# New Download and Explore Icons
This PR is the first in a series of PRs to add new export UI and functionality to tile footers. For an example of the end-goal, see the screenshots in PR #4205.

## Changes
This PR:
* Adds a new URL flag to enable the new icons, to hide the feature until all elements are implemented and tested
* Adds a new utils for adding such flags in the future
* Adds new components for rendering clickable icons in the tile footers
* Adds a new chart download modal, based on the old "chart embed" modal, but refactored and rewritten as a functional component
* Renames old "embed" element references to "download" to remove confusion with the upcoming "embed as web component" action

The following are left for future PRs:
* Adding a new "embed as a web component" action
* Adding a new NL feedback action
* Enabling this functionality on the web components 

With this change, the new icons are can be enabled on the explore pages and new visualization tools by adding `&chartIcons=true` to the end of the URL. On the disaster and sustainability dashboards, add `#chartIcons=true`.

## Screengrabs:

### Explore Page

https://github.com/datacommonsorg/website/assets/4034366/2f88dc6b-d602-4687-9c89-fb825f587414

### Visualization Tools

<img width="1718" alt="Screenshot 2024-05-13 at 9 39 51 AM" src="https://github.com/datacommonsorg/website/assets/4034366/1859824a-97cb-46cb-9789-93fdbfc2a85c">

<img width="1262" alt="Screenshot 2024-05-13 at 10 11 16 AM" src="https://github.com/datacommonsorg/website/assets/4034366/14368edb-7a14-4869-a35d-b5fc51c74fb1">

### Disaster Dashboard (Only top event tile has export available)

<img width="1140" alt="Screenshot 2024-05-13 at 9 37 24 AM" src="https://github.com/datacommonsorg/website/assets/4034366/f251c389-245d-41dd-a161-219c101267ad">

<img width="1229" alt="Screenshot 2024-05-13 at 10 12 22 AM" src="https://github.com/datacommonsorg/website/assets/4034366/696cdd96-028a-41d7-923c-be8e6a6d1c29">

2024-05-13 18:36 UTC, juliawu commented on static/package.json
> +    "query-string": "^7.1.3",
Needed to downgrade to v7 because this package moved to Pure ESM in v8, which breaks our jest testing.

2024-05-17 23:40 UTC, dwnoble requested changes

2024-05-17 23:40 UTC, dwnoble commented on static/js/components/tiles/chart_action_icons.tsx
> +        onClick={props.onClickHandler}
if there's no passed in url, add event.preventDefault() here

2024-05-17 23:40 UTC, dwnoble commented on static/js/components/tiles/chart_action_icons.tsx
> +      {linkIsReady && (
Can you just check if linkRef.current is truthy here?

2024-05-17 23:40 UTC, dwnoble commented on static/js/components/tiles/chart_action_icons.tsx
> +function ActionIcon(props: ActionIconPropType): JSX.Element {
This looks pretty similar to some of the new biomedical buttons- is it possible to merg them? (maybe an exercise for the future)

2024-05-17 23:40 UTC, dwnoble commented on static/js/components/tiles/chart_action_icons.tsx
> +  container?: HTMLElement;
is it necessary to set the container in the tooltips? maybe it is- something to do with tooltip rendering in a web component?

2024-05-17 23:40 UTC, dwnoble commented on static/js/components/tiles/chart_action_icons.tsx
> +            url={props.exploreLink?.url}
Nit: remove `?`

2024-05-17 23:40 UTC, dwnoble commented on static/js/components/tiles/chart_action_icons.tsx
> +              triggerGAEvent(GA_EVENT_TILE_DOWNLOAD, {
Could the page navigation complete before the ga event?
https://stackoverflow.com/a/50062249

2024-05-17 23:40 UTC, dwnoble commented on static/js/components/tiles/chart_footer.tsx
> +  useChartActionIcons?: boolean;
Can we completely encapsulate whether the dev flag is turned on or not within the actual chart footer component? This way the upstream components (block.tsx, vis tools, etc) don't need to know that there's a dev flag set or not

2024-05-17 23:40 UTC, dwnoble commented on static/js/utils/dev_flag_utils.ts
Nice!
To be more consistent with other google infra, can we name this "experiment_flag_utils.ts'?

2024-05-17 23:40 UTC, dwnoble commented on static/js/utils/dev_flag_utils.ts
> +  USE_CHART_ACTION_ICONS_FLAG: "chartIcons",
Maybe prefix flags with something like "experiment" so its clear in the url params that it's for an experiment?

2024-05-17 23:40 UTC, dwnoble commented on static/js/utils/dev_flag_utils.ts
> +export function isFlagSet(flag: string): boolean {
Rename: isExperimentEnabled

2024-05-17 23:43 UTC, dwnoble reviewed
Thanks Julia!
Some style suggestions (cc @miss-o-soup )
![nb-map-page](https://github.com/datacommonsorg/website/assets/13766/a5838921-9529-4d1e-a0a2-ac3c1fbead81)


![nb-mobile-modal](https://github.com/datacommonsorg/website/assets/13766/e246c5ac-fa28-4b54-879d-fabd34261280)

Can you add a loading indicator (or just an empty text area placeholder) when opening the modal?
<img width="1204" alt="Screenshot 2024-05-17 at 3 47 22 PM" src="https://github.com/datacommonsorg/website/assets/13766/484e9a58-ec0e-4e90-8648-80dabbfd3423">

2024-05-17 23:43 UTC, dwnoble commented on static/js/components/tiles/chart_action_icons.tsx
> +      <a
It's a little hard to describe, but im seeing the mouse "flicker" between a pointer and an arrow when i hover over this icon. are you seeing that?

2024-07-15 16:49 UTC, juliawu commented
Closing because this work has been deprioritized. Will return to this once higher priority projects are completed.

2024-07-15 16:49 UTC, closed without merging