Global header search
datacommonsorg/website pull request #4740
Opened 2024-11-18 00:49 UTC by nick-nlb

### Description

The purpose of this PR is to have the search bar in the header on all pages. 

Previously, pages by default did not have the search in the header, and had to be flagged in order to provide the search bar. Now, this flag is reversed and pages will contain the header search by default.

The search bar has been removed from the explore page, and the more complicated search functionality provided in that page (such as the ability to programmatically change the current query and provide a debug modal) is now available to the universal search bar in the header.

Related layout updates have been made to ensure that the explore page displays correctly with the internal search now gone, and the debug "bug" button is now aligned nicely (with the global search at the top). The debug modal has also been revamped.

### Notes

When the search bar was inline in the explore page, that page could interact and share state with its inline search. This allowed the explore page to provide and programmatically update the query string as well as to provide debugging information, among other things.

We now have to communicate that information from the explore page all the way to the header. Normally, we might consider options like React context, or lifting of state. 

However, in this case, the header and the explore page are in totally separate React apps with separate mount points, and that limits our ability to use more traditional methods to communicate this data.

The solution implemented was to create a global "Query Store", that can be updated by a component in one app, and then have those changes provided to a component in another app. The query store provides a hook to facilitate this communication. This allows these otherwise completely independent applications to communicate with each other in a reactive way.

2024-11-21 02:58 UTC, gmechali approved these changes
Thanks Nick! Looks great, just curious what kind of testing you've done on this?
Also please wait for Dan's review still as I'm still newish to the DC codebase, so a secondary reviewer is more prudent.

2024-11-27 00:12 UTC, dwnoble requested changes
Thanks Nick & Pablo- i like this approach.

I'm seeing an error when i run in "custom DC" mode (`./run_server.sh -m -e custom`):

![Screenshot 2024-11-26 at 3 47 18 PM](https://github.com/user-attachments/assets/b156556c-9520-433d-8035-102aba4c9840)

This might be a little more involved to fix. some potential options:

(1) in custom dc mode, keep the search bar inline on the explore page
(2) update custom dc headers (in `server/templates/custom_dc/**/base.html`) to include a search bar. Maybe this means attaching the `HeaderBarSearch` to some new ID in the custom DC navbar, or it could be a pure-flask inlined search bar

What do you think?

2024-11-27 00:12 UTC, dwnoble commented on static/js/shared/stores/query_store_hook.tsx
> +  useEffect(() => {
Can you add a comment describing the useEffect?

2024-11-27 00:12 UTC, dwnoble commented on static/js/shared/stores/query_store_hook.tsx
> +      changeType:
Can you reuse the ChangeType type here?

2024-11-27 00:12 UTC, dwnoble commented on static/js/shared/stores/query_store_hook.tsx
> +export const useQueryStore = (): QueryStoreData => {
Nice job building out this hook!

2024-11-27 00:12 UTC, dwnoble commented on static/js/types/app/explore_types.ts
> +  rerank_score: number;
Good catch

2024-11-27 00:12 UTC, dwnoble commented on server/templates/base.html
> +<script src={{url_for('static', filename='queryStore.js', t=config['VERSION'])}} async></script>
Can you add this to all of the `server/templates/custom_dc/**/base.html` files?

2024-11-27 00:13 UTC, dwnoble commented
Also i saw a small difference in padding between the search bar in the visualization tools and the knowledge graph:

![header-visualization-tools](https://github.com/user-attachments/assets/236f1159-ae34-4cfa-8de8-661b52867f5c)
![header-knowledge-graph](https://github.com/user-attachments/assets/2f0913f7-349c-4ce4-84d4-bbaab006d554)

2024-11-27 17:59 UTC, dwnoble commented
> > Thanks Nick & Pablo- i like this approach.
> > I'm seeing an error when i run in "custom DC" mode (`./run_server.sh -m -e custom`):
> > This might be a little more involved to fix. some potential options:
> > (1) in custom dc mode, keep the search bar inline on the explore page (2) update custom dc headers (in `server/templates/custom_dc/**/base.html`) to include a search bar. Maybe this means attaching the `HeaderBarSearch` to some new ID in the custom DC navbar, or it could be a pure-flask inlined search bar
> > What do you think?
> 
> Thank you for catching that! The error itself is fixed by including the store in the various base templates, but that leaves the question of how to implement the search bar in explore pages that don't use the standard header.
> 
> I would go with option 1 for this PR, because having the inline explorer search as an option (tied to the flag) will allow for all cases, including ones where a custom header implementation doesn't have it (and will give us the flexibility to use it if we do want to later).
> 
> It actually won't be a big task to restore the inline explorer search. It already does work with the header store functionality and so we really would just need to restore it and then tie its display to the flag that determines if the header search displays (if the header search flag is false, we display the inline search).
> 
> However, it could be nice to also do option 2 as a separate PR, to move towards having the header bar search as the default standard!
> 
> Let me know if you are happy with option 1 and I will implement that. All the other comments addressed!

Option 1 sounds good to me! And agreed that option 2 can come later, but i dont think it's urgent

2024-12-07 03:29 UTC, dwnoble approved these changes
Looks great! Thanks Nick.

One final request: can you remove the navbar search from the /place/* page? The place page has a separate search when you click "Change Place", and we don't want to show users two search bars.

(This will be moot in a few weeks, as we're planning on rolling out a new, re-designed version of the place page that can have the top search bar added back in)

2024-12-09 17:30 UTC, dwnoble commented
> Looks great! Thanks Nick.
> 
> One final request: can you remove the navbar search from the /place/* page? The place page has a separate search when you click "Change Place", and we don't want to show users two search bars.
> 
> (This will be moot in a few weeks, as we're planning on rolling out a new, re-designed version of the place page that can have the top search bar added back in)

Sorry for being wishy washy on this- after a little more internal discussion, can you **leave the navbar search box on the place page in place**.  We'll separately remove the "change place" search box altogether.

2024-12-09 21:31 UTC, merged